### ISSUE TITLE
AttributeError: 'ResNet' object has no attribute 'module'

### ISSUE THREAD

**Issue by zhengziqiang** [zhunzhong07/HHL#1]
When I run python HHL.py -s duke -t market --logs-dir logs/duke2market-HHL,
It occurs an error:

Traceback (most recent call last):
  File "/media/vision/43c620be-e7c3-4af9-9cf6-c791ef2ed83e/zzq/reid/HHL-master/HHL.py", line 231, in <module>
    main(parser.parse_args())
  File "/media/vision/43c620be-e7c3-4af9-9cf6-c791ef2ed83e/zzq/reid/HHL-master/HHL.py", line 128, in main
    if hasattr(model.module, 'base'):
  File "/home/vision/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'module'

**Comment by zhengziqiang** [comment]
I comment this and it works, maybe this could get a bad result!

    # base_param_ids = set(map(id, model.module.base.parameters())) \
    #                  | set(map(id, model.module.triplet.parameters())) \
    #                  | set(map(id, model.module.feat.parameters())) \
    #                  | set(map(id, model.module.feat_bn.parameters()))
    #
    # new_params = [p for p in model.parameters() if
    #               id(p) not in base_param_ids]
    # param_groups = [
    #     {'params': model.module.base.parameters(), 'lr_mult': 0.1},
    #     {'params': new_params, 'lr_mult': 1.0}]

**Comment by zhunzhong07** [comment]
could you try to run the code with pytorch=0.4.0?

**Comment by zhunzhong07** [comment]
Hi, this error happened when your device only has one GPU. We have fixed this bug now.  [Fix 'module' error](https://github.com/zhunzhong07/HHL/commit/5e6599a40bdc60a4a919cf415184834f39ec4d29)

**Comment by tiannandyjx** [comment]
Hello, is the problem solved? I also encountered the same problem as you.

**Comment by xiaoaoran** [comment]
same problem. Does anyone know how to solve it?

**Comment by quocnhat** [comment]
just usingDataParallel solve this problem.
