### ISSUE TITLE
HHL's Mean AP: 9.4%

### ISSUE THREAD

**Issue by TJJTJJTJJ** [zhunzhong07/HHL#2]
Hi, when I run 
```python
python baseline.py -s duke -t market --logs-dir logs/duke2market-baseline
```
the result is almost like thing you release.
But when I run
```python
python HHL.py -s duke -t market --logs-dir logs/duke2market-HHL --data-dir ./data -b 16
```
and the starGAN is yours.
the results is like
Mean AP: 9.4%
CMC Scores
  top-1          26.5%
  top-5          43.5%
  top-10         52.7%
  top-20         61.6%
Maybe something I set it wrong, if you are free, pleace check me out.
Thank you, sir.

**Comment by zhunzhong07** [comment]
The batch size should be 128.

**Comment by TJJTJJTJJ** [comment]
I have only one GPU, if the batch size is 128, the cuda memory is not enough, so I set the batch size is 16. Does batch size has a great influences about HHL? what should I do, may you give me some idea in such enviroment?

**Comment by TJJTJJTJJ** [comment]
epoch or lr or other things may help the result when batch size is low? How many GPU when you run the code?

**Comment by zhunzhong07** [comment]
I use two GPUs to run our method. Batch size = 8 is too small for converging.
