### ISSUE TITLE
the method of mean_ap

### ISSUE THREAD

**Issue by TJJTJJTJJ** [zhunzhong07/HHL#3]
Hi,
I'm sorry to bother you again. I'm confused about your code about mAP.
In open-reid, it's like
```python
from sklearn.metrics import average_precision_score
aps.append(average_precision_score(y_true, y_score))
# examples
>>> import numpy as np
>>> from sklearn.metrics import average_precision_score
>>> y_true = np.array([0, 0, 1, 1])
>>> y_scores = np.array([0.1, 0.4, 0.35, 0.8])
>>> average_precision_score(y_true, y_scores)  
0.83...
# after sort by y_socres, it's 1, 0, 1, 0
# recall= [1.  0.5 0.5 0. ], pre = [0.66666667 0.5        1.         1.        ],
# -np.sum(np.diff(recall) * np.array(precision)[:-1])
# 0.83 = 1/2*2/3+0*1/2+1/2*1= 5/6
```
In your code, it's like
def average_precision_score(y_true, y_score, average="macro",
                            sample_weight=None):
    def _binary_average_precision(y_true, y_score, sample_weight=None):
        precision, recall, thresholds = precision_recall_curve(
            y_true, y_score, sample_weight=sample_weight)
        return auc(recall, precision)

    return _average_binary_score(_binary_average_precision, y_true, y_score,
                                 average, sample_weight=sample_weight)
# examples
>>> import numpy as np
>>> from sklearn.metrics import average_precision_score
>>> y_true = np.array([0, 0, 1, 1])
>>> y_scores = np.array([0.1, 0.4, 0.35, 0.8])
>>> average_precision_score(y_true, y_scores)  
0.7916666666666666
# recall= [1.  0.5 0.5 0. ], pre = [0.66666667 0.5        1.         1.        ],
# after I calculate, it's like
# 0.79 = 1/2*(2/3+1/2)*1/2+0*(1/2+1)*1/2+1/2*(1+1)*1/2 = 19/24
# it's like get the medium value rather than one value
# I think even if it gets the medium value, it should be like
# 1/2*(2/3+1)*1/2+0*(1/2+1)*1/2+1/2*(1+1)*1/2 = 11/12
```
Maybe there are something I get wrong. Or if you are free, please check me out.
I am trying to understand better your code.
Thank you, sir.

**Comment by TJJTJJTJJ** [comment]
Hi,
I'm sorry to bother you again. I'm confused about your code about mAP.
In open-reid, it's like
```python
from sklearn.metrics import average_precision_score
aps.append(average_precision_score(y_true, y_score))
# examples
>>> import numpy as np
>>> from sklearn.metrics import average_precision_score
>>> y_true = np.array([0, 0, 1, 1])
>>> y_scores = np.array([0.1, 0.4, 0.35, 0.8])
>>> average_precision_score(y_true, y_scores)  
0.83...
# after sort by y_socres, it's 1, 0, 1, 0
# recall= [1.  0.5 0.5 0. ], pre = [0.66666667 0.5        1.         1.        ],
# -np.sum(np.diff(recall) * np.array(precision)[:-1])
# 0.83 = 1/2*2/3+0*1/2+1/2*1= 5/6
```
In your code, it's like
```
def average_precision_score(y_true, y_score, average="macro",
sample_weight=None):
def _binary_average_precision(y_true, y_score, sample_weight=None):
precision, recall, thresholds = precision_recall_curve(
y_true, y_score, sample_weight=sample_weight)
return auc(recall, precision)

return _average_binary_score(_binary_average_precision, y_true, y_score,
                             average, sample_weight=sample_weight)
```
```
# examples
import numpy as np
from sklearn.metrics import average_precision_score
y_true = np.array([0, 0, 1, 1])
y_scores = np.array([0.1, 0.4, 0.35, 0.8])
average_precision_score(y_true, y_scores)
0.7916666666666666
```
recall= [1. 0.5 0.5 0. ], pre = [0.66666667 0.5 1. 1. ],
after I calculate, it's like
0.79 = 1/2*(2/3+1/2)1/2+0(1/2+1)1/2+1/2(1+1)*1/2 = 19/24
it's like get the medium value rather than one value
I think even if it gets the medium value, it should be like
1/2*(2/3+1)1/2+0(1/2+1)1/2+1/2(1+1)*1/2 = 11/12

Maybe there are something I get wrong. Or if you are free, please check me out.
I am trying to understand better your code.
Thank you, sir.

**Comment by zhunzhong07** [comment]
Hi, this problem is explained at [here](https://github.com/huanghoujing/person-re-identification-check-eval-code) by @huanghoujing . In our code, we use the "average_precision_score" of version-0.18.1, but in open-reid, the "average_precision_score" will be different in version-0.19. Our result is the same as the official evaluation code.
