### ISSUE TITLE
ValueError: num_samples should be a positive integeral value, but got num_samples=0

### ISSUE THREAD

**Issue by SpiritBear000** [zhunzhong07/HHL#9]
When i try baseline.py, i got this error.
![捕获](https://user-images.githubusercontent.com/32519071/57762107-6c902680-7731-11e9-9256-f30eada9da00.PNG)

when i tracked to https://github.com/zhunzhong07/HHL/blob/7ea2655038d0e0654f22f751af5c12c6e8de6ffe/reid/datasets/domain_adaptation.py#L23
i found that these data are assigned with '[]'. Is it meaning that i should replace it with my dataset when i run this code?

**Comment by zhunzhong07** [comment]
Yes, you should first download datasets to the folder 'data/'.

**Comment by SpiritBear000** [comment]
i have known what's wrong with me.   i named my filename as '[My_ReID]'. The '[' and ']' made glob.glob() doesn't work.
![捕获](https://user-images.githubusercontent.com/32519071/57768174-a6ffc080-773d-11e9-9432-c3aee995c81c.PNG)

Thank you for your immediately replying!
